name: Build and Release for GameAssitant

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: windows-latest

    env:
      Project_File: GameAssitant.csproj
      Configuration: Release
      Platform: x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore ${{ env.Project_File }}

    - name: Build the project
      run: msbuild ${{ env.Project_File }} /p:Configuration=${{ env.Configuration }} /p:Platform=${{ env.Platform }} /p:SignManifests=false /verbosity:minimal

 

    - name: Create release directory
      run: |
        if (-Not (Test-Path release)) {
          New-Item -ItemType Directory -Path release
        }
      shell: pwsh

    - name: Generate timestamped zip file
      id: timestamp
      run: |
        $timestamp = (Get-Date -Format "yyyyMMddHHmm")
        echo "ZIP_FILENAME=release/GameAssitant$timestamp.zip" >> $GITHUB_ENV
       
      shell: pwsh

    - name: Compress build output
      run: Compress-Archive -Path bin\x64\Release\* -DestinationPath ${{ env.ZIP_FILENAME }}
      shell: pwsh

    - name: Upload to GitHub Releases
      uses: ncipollo/release-action@v1
      with:
        artifacts: release/build.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        name: "Build Release"
        body: "Automated release for the latest build."
        draft: false
        prerelease: false
